export const texts = {
  action: 'Action',
  browserLabel: 'Parcourir votre appareil',
  calico: 'CALICO',
  clients: 'Clients',
  displayFilters: 'Afficher les filtres',
  displayFolderProperties: 'Voir les propriétés du dossier',
  dragLabel: 'Glissez vos documents ici',
  filter: 'filtrer',
  folderName: 'Nom du Dossier',
  folderProperties: 'Propriétés du dossier',
  hideFilters: 'Masquer les filtres',
  history: 'Historique',
  individualContract: 'Contrat Individuel',
  lifeCycle: 'Cycle de vie',
  manageFilters: 'Gérer les filtres',
  metaData: 'Métadonnées',
  newFolder: 'Nouveau dossier',
  rights: 'Droits',
  searchInFilters: 'Chercher dans les filtres',
  seeDirectoryTree: "Voir l'arborescence",
  send: 'Envoyer',
  validateModification: 'Valider les modifications',
};
