export const texts = {
  activeFilters: 'filtres actifs',
  all: 'Tous',
  andThe: 'Et le',
  author: 'autheur',
  between: 'Entre le',
  classicContract: 'Contrat classique',
  clientName: 'Nom du client',
  contractDuration: 'Durée du contrat',
  contracts: 'Contrats',
  date: 'date de publication',
  desc: 'description',
  displayNbResult: (number: number): string => {
    return `Affiche ${number} résultats`;
  },
  file: 'fichier',
  filter: 'filtrer',
  filterName: 'Nom du filtre',
  fixedTermContract: 'CDD',
  freelance: 'Freelance',
  invoice: 'Factures',
  location: 'emplacement',
  particular: 'Particulier',
  period: 'période',
  permanentContract: 'CDI',
  relevance: 'pertinence',
  removeAll: 'Supprimer tout',
  seeFilters: 'Voir les filtres',
  seeThe: 'Voir les',
  selected: 'sélectionné',
  sortBy: 'Trier par',
  specialContract: 'Contrat special',
  title: 'titre',
  typeOfContract: 'Type de contrat',
};
