export const texts = {
  applicationInProgress: 'EN COURS DE CANDIDATURE',
  beforeYesterday: 'Avant-hier',
  beingSigned: 'en cours de signature',
  cardListUploadText: 'Ma carte de tiers payant',
  currentlyUnderConsultation: 'en cours de consultation',
  duringTheProcedure: 'en cours de procédure',
  fence: 'cloturé',
  finish: 'terminé/signé',
  firstDecember2023: 'Le 01 décembre 2023',
  fiveTeenDecember2023: 'Le 15 décembre 2023',
  headerSubTitle: 'sous-titre',
  headerTitle: 'Element de text',
  heightDecember2023: 'Le 08 décembre 2023',
  iconCardSubtitle: 'sous-titre',
  iconCardTitle: 'Mes documents',
  inProgress: 'En cours',
  myBill: 'Ma facture du 12/12/23',
  myResidenceCertificate: 'Mon attestation de domicile',
  notifications: 'Notifications',
  onBreak: 'En pause',
  tenDecember2023: 'Le 10 décembre 2023',
  threeHoursAgo: 'Il y a 3h',
  twentyDecember2023: 'Le 20 décembre 2023',
  twentySeven2023: 'Le 27 Novembre 2023',
  valid: 'Validé',
  viewMore: 'Voir plus',
};
